name: client_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  http: ^0.13.5
  pos_server:
    git:
      url: https://github.com/clover-leaf/pos_server.git
      ref: master
  web_socket_client: ^0.1.0-dev.1

dev_dependencies:
  test: ^1.21.0
  very_good_analysis: ^4.0.0
