name: client_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^0.13.5
  rxdart: ^0.27.7
  uuid: ^3.0.7
  web_socket_client: ^0.1.0-dev.1

dev_dependencies:
  build_runner: ^2.3.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.2
  test: ^1.21.0
  very_good_analysis: ^4.0.0
